### ISSUE TITLE
Refresh issues and the colors are now blue

### ISSUE THREAD

**Issue by craigbloodworth** [TheInformationLab/Tableau-Extension-ExportAll#59]
We are still having the refresh issues and the colors are still blue...

_Originally posted by @LyleEllerbach in https://github.com/TheInformationLab/Tableau-Extension-ExportAll/issues/58#issuecomment-681112608_

**Comment by craigbloodworth** [comment]
@LyleEllerbach the colour changed to blue as Tableau modified their official React UI framework which changed the primary style from green to blue and so the extension is now in keeping with the rest of the updated Tableau UI.

As for the refresh issue could you please confirm the version of Tableau you're running as well as a screenshot of your browser console so I can try & diagnose the issue

**Comment by miko-1** [comment]
Hi @craigbloodworth , I'm facing the same issue as @LyleEllerbach.

I'm running it on Tableau desktop version 2019.3.5, and below is the error I see in the console-
![image](https://user-images.githubusercontent.com/70293666/91358217-0c9f8100-e7b8-11ea-838a-112cef8b3acf.png)

**Comment by craigbloodworth** [comment]
@miko-1 it's the late evening here in the UK so I won't be able to check until the morning but those errors you posted look to be coming from vqlweb.js which is a Tableau js file, not the extension code. That doesn't mean the extension isn't causing it, but it's less likely

**Comment by miko-1** [comment]
Hi @craigbloodworth, thanks for your reply, sorry didn't mean to bother you in late night. Below is the screenshot I just took I think it should be relevant to the refresh issue. Really appreciate it if you could take a look in the morning! Have a good night!

![image](https://user-images.githubusercontent.com/70293666/91359143-98fe7380-e7b9-11ea-8657-b66844273169.png)

**Comment by craigbloodworth** [comment]
@miko-1 @LyleEllerbach I can't replicate the refresh issue using my instance of Tableau Server 2020.2. I'm now building a 2019.3.5 server. @LyleEllerbach could you please confirm your version of Tableau Server?

**Comment by jackragan** [comment]
@craigbloodworth I work with both @jessicalois @haniunc. We are still having the same issue.  We are using 2020.1.3.  If there is something you need us to test we will be more than happy to help.

**Comment by LyleEllerbach** [comment]
Good morning.  Our server version is Tableau Server Version: 2020.2.3 (20202.20.0626.1424) 64-bit Linux.

Just got to the office (6:30AM here).  Let me know what else I can do to help.

**Comment by craigbloodworth** [comment]
I've just pushed what I believe is a fix, however as I can't yet replicate locally I'm unable to verify. Perhaps you could check for me? @LyleEllerbach @jackragan

**Comment by LyleEllerbach** [comment]
Is there anything I need to do for the push to take affect?   In not then the issue still exists.  Dashboards with Export All load and then after about 4 seconds the do a complete refresh.

**Comment by LyleEllerbach** [comment]
Also I did notice that when I use the Export All with this new push the ordering of the columns is not as it was yesterday.  The order is now very random.   However, I can deal with this if the refresh issue is resolved.  LOL!

**Comment by steffidhingra** [comment]
> Also I did notice that when I use the Export All with this new push the ordering of the columns is not as it was yesterday. The order is now very random. However, I can deal with this if the refresh issue is resolved. LOL!

@LyleEllerbach, i am also getting same issue related to ordering of columns and strange part is even after saving the order of columns, its not getting changed.

**Comment by LyleEllerbach** [comment]
> > Also I did notice that when I use the Export All with this new push the ordering of the columns is not as it was yesterday. The order is now very random. However, I can deal with this if the refresh issue is resolved. LOL!
> 
> @LyleEllerbach, i am also getting same issue related to ordering of columns and strange part is even after saving the order of columns, its not getting changed.

Are you getting the refresh issue too?

**Comment by steffidhingra** [comment]
> > > Also I did notice that when I use the Export All with this new push the ordering of the columns is not as it was yesterday. The order is now very random. However, I can deal with this if the refresh issue is resolved. LOL!
> > 
> > 
> > @LyleEllerbach, i am also getting same issue related to ordering of columns and strange part is even after saving the order of columns, its not getting changed.
> 
> Are you getting the refresh issue too?

I noticed twice. After that it was not happening.

**Comment by jackragan** [comment]
@craigbloodworth I just test it on our server and I am not getting the refresh issue. But when I actually try the download button it downloads, but there is nothing in the spreadsheet.

**Comment by LyleEllerbach** [comment]
I'm also getting instances where I have multiple download options some are grayed out that were available before yesterday's push update.

![Options](https://user-images.githubusercontent.com/52171091/91440309-05b65400-e834-11ea-8256-1ebdc5cd5de3.png)

**Comment by miko-1** [comment]
@craigbloodworth Thanks for getting back to us. This is our server version: Tableau Server Version: 2019.3.1 (20193.19.1017.1259) 64-bit Windows. And the refreshing issue still persist for me.

**Comment by LyleEllerbach** [comment]
Here is our Console screenprint.

![Console](https://user-images.githubusercontent.com/52171091/91443609-2d5beb00-e839-11ea-8e71-5e5d5ae572bd.png)

**Comment by LyleEllerbach** [comment]
I hate to ask this... but this is causing significant issues for our hospital users here in the US... is it possible to revert back to the previous version that didn't have these issues?

**Comment by jessicalois** [comment]
We are also experiencing issues for ~1,800 users. We have had the same thought that reverting to the old version would be helpful. At the same time, I also hate to ask it because I know Craig has put a lot of work into this. Craig, if you're reading this, thank you for all the time you've poured into this extension and making it available to the public Tableau community. Our team is looking forward to this being resolved one way or the other and we appreciate you.

**Comment by craigbloodworth** [comment]
@LyleEllerbach I've pushed a fix for the error you've been able to highlight in the console.

As for requests for rolling back to the previous release this isn't something I'm prepared to do as I need to be able to move the code forward in order to address some other issues and requests. If you want to go back to the previous release it is possible to self host this on your own web server using the packaged code available [for download](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/releases/tag/2.1.1)

**Comment by miko-1** [comment]
@craigbloodworth , looks like the refreshing issue is resolved on Tableau Server Version: 2019.3. and I don't observe the column order issue. Thank you so much for the quick fix and really appreciate your time and effort!

**Comment by haniunc** [comment]
Hi @craigbloodworth ,

After the last update, I am seeing 3 different issues. 

First, there are some buttons that produce and empty excel file initially. However, if i press Ctrl-F5 and then press the buttons again, they work fine. Here is the error log from before I refresh the page:
![reload one](https://user-images.githubusercontent.com/53050839/91451770-bed45880-e84b-11ea-82d6-9b85e3d3ee8a.JPG)


Second are buttons that are still grayed out. Here is their error log:
![grayed out](https://user-images.githubusercontent.com/53050839/91451933-f9d68c00-e84b-11ea-9a4b-37885f14e974.JPG)


And finally, here is one where the button displays correctly, but after pressing the button, nothing happens.  
![no response](https://user-images.githubusercontent.com/53050839/91452000-1246a680-e84c-11ea-8fa5-f326415c5ed4.JPG)


Hopefully this information can help. If there are any other screenshots or error messages that you would like us to look for, please let me know. Thanks again for all your help with this.

**Comment by LyleEllerbach** [comment]
> @LyleEllerbach I've pushed a fix for the error you've been able to highlight in the console.
> 
> As for requests for rolling back to the previous release this isn't something I'm prepared to do as I need to be able to move the code forward in order to address some other issues and requests. If you want to go back to the previous release it is possible to self host this on your own web server using the packaged code available [for download](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/releases/tag/2.1.1)

Is the download here the version before yesterday's updates?

**Comment by LyleEllerbach** [comment]
As I continue to work with our clients calling with issues we are now experiencing all download files being completely empty.  The file is built but no data is included.

**Comment by craigbloodworth** [comment]
@LyleEllerbach have you tried replacing the extension in an existing dashboard using the latest trex file which can be [downloaded here](https://raw.githubusercontent.com/TheInformationLab/Tableau-Extension-ExportAll/master/ExportAll.trex)

**Comment by LyleEllerbach** [comment]
> @LyleEllerbach have you tried replacing the extension in an existing dashboard using the latest trex file which can be [downloaded here](https://raw.githubusercontent.com/TheInformationLab/Tableau-Extension-ExportAll/master/ExportAll.trex)

When I click the link it loads a web page.  Is it supposed to download the trex file?

**Comment by craigbloodworth** [comment]
Just save the contents as a .trex file

**Comment by LyleEllerbach** [comment]
> Just save the contents as a .trex file

So on Desktop this file works correctly generated the expected XLSX files with the correct content.  On Server, the dashboard refresh still happens and the XLSX files are all empty.

**Comment by craigbloodworth** [comment]
@LyleEllerbach If I give you a secure upload location is it possible to provide a packaged workbook?

**Comment by steffidhingra** [comment]
> Just save the contents as a .trex file

@craigbloodworth I save the content as .trex file and added new extension but still order sequence is incorrect.

**Comment by craigbloodworth** [comment]
I have implemented a fix to the extension, essentially reversing a solution to handle duplicate fields with the same field name in a sheet. This will cause strange behaviour in the output if you have duplicate field names but should fix issues experienced over the past 48 hours.

To give some background the issue I was trying to resolve is when the extensions sdk surfaces two field names with exactly the same field name. This happens when you have a standard aggregate and a quick table calc such as SUM(SALES) and a running average SUM(Sales) in the same sheet. The sdk provides those fields as:
![image](https://user-images.githubusercontent.com/8116300/91547992-9c5e4000-e91c-11ea-8aec-bfa9066d46d6.png)

My solution in the latest version was to make use of the index field in combination with the field name to differentiate between the two fields. In this instance the extension meta would reference them as "1.SUM(Sales)" and "2.SUM(Sales)" however it wasn't detected during testing that a simple change in the ordering of fields in the viz, and potentially other interactions, would modify this index field. Therefore the extension's meta info and the viz meta info could quickly get out of sync causing fields not to be exported.

For those affected by the issue please accept my apologies. I hope that the fix has indeed resolved the issues you were having. Please know that the change came from a place of wanting to improve the extension & resolve issues others have reported when having to handle duplicate field names.

If a few could possibly comment to confirm that the issue is indeed resolved I will close the issue. If the extension still isn't giving you the output you're looking for could I ask that you try using the reset button and reconfiguring the fields before testing again.

**Comment by LyleEllerbach** [comment]
Unfortunately we are still experiencing the refresh issue.  I removed all Export All extension objects from the dashboard,  reloaded the .trex from the Extension Gallery and placed a new Export All extension object on the dashboard.  Configured it and published the dashboard.   Once the dashboard loads there is a 4 second pause and the entire dashboard still refreshes.

**Comment by craigbloodworth** [comment]
@LyleEllerbach are you able to provide either a packaged workbook or screenshots of the browser console? Without either of these I'm unable to diagnose the issue you're experiencing.

**Comment by LyleEllerbach** [comment]
Yes I can provide the twbx how can I attach it?

**Comment by craigbloodworth** [comment]
> Yes I can provide the twbx how can I attach it?

Drop the file into [this secure file drop](https://fileshare.theinformationlab.co.uk/index.php/s/puLCy00gDHKr67D)

**Comment by LyleEllerbach** [comment]
> > Yes I can provide the twbx how can I attach it?
> 
> Drop the file into [this secure file drop](https://fileshare.theinformationlab.co.uk/index.php/s/puLCy00gDHKr67D)

I just uploaded.   Thank you for all your help!

**Comment by Rahulhgupta** [comment]
@craigbloodworth is it really tough to go back to previous  version  that was working  well.
I am still facing issue

**Comment by craigbloodworth** [comment]
@LyleEllerbach sadly I've been unable to replicate. I've tested on 2020.2 Desktop and 2019.3 Server (Chrome, Edge, IE11). Desktop shows no errors in the debugger and the refreshing behaviour doesn't happen with Server. I'm currently upgrading my 2019.3 test server to 2020.2.3 to confirm in your exact version but as it stands I'm unable to offer any more support. I'll update if this changes at all

**Comment by LyleEllerbach** [comment]
> @craigbloodworth is it really tough to go back to previous version that was working well.
> I am still facing issue

Are you having the refresh issue as well?

**Comment by LyleEllerbach** [comment]
> @craigbloodworth is it really tough to go back to previous version that was working well.
> I am still facing issue

Are you having the refresh issue too?

**Comment by craigbloodworth** [comment]
> @craigbloodworth is it really tough to go back to previous version that was working well.
> I am still facing issue

Can you give me some more info regarding the issue you have? Can you please include screenshots of any errors in your browser's console?

**Comment by steffidhingra** [comment]
> > @craigbloodworth is it really tough to go back to previous version that was working well.
> > I am still facing issue
> 
> Can you give me some more info regarding the issue you have? Can you please include screenshots of any errors in your browser's console?

@craigbloodworth , Please see my comments for the issue in : 
https://github.com/TheInformationLab/Tableau-Extension-ExportAll/issues/60#issuecomment-682628021

**Comment by haniunc** [comment]
Hi @craigbloodworth ,
In our dashboards, when it is first loaded, no data is selected and the user selects a practice from a drop down which populates the table. It seems like this is causing an issue with the blank export. If we have one pre-selected before we upload it to the server, it works fine. I can send you a packaged workbook to test this out. Another issue (also appearing in that workbook) is buttons that do nothing when you click on them. Should I use the same link above to send you the dashboard, or is there another link I should use?

Again, we are using Tableau 2020.1.0 and Chrome for the browser.

**Comment by craigbloodworth** [comment]
> Hi @craigbloodworth ,
> In our dashboards, when it is first loaded, no data is selected and the user selects a practice from a drop down which populates the table. It seems like this is causing an issue with the blank export. If we have one pre-selected before we upload it to the server, it works fine. I can send you a packaged workbook to test this out. Another issue (also appearing in that workbook) is buttons that do nothing when you click on them. Should I use the same link above to send you the dashboard, or is there another link I should use?
> 
> Again, we are using Tableau 2020.1.0 and Chrome for the browser.

Thanks for the description @haniunc. That is a specific use case which is separate from the issues listed above. I can see how a recent change could cause this to happen. I can remove part of this change which should solve that specific use case. It's deploying now and will be live in the next few minutes

**Comment by LyleEllerbach** [comment]
Here is a snapshot of the console log as well as the full log saved to a .log file.  Hope this helps.
![Console Log](https://user-images.githubusercontent.com/52171091/91583464-e17f7380-e916-11ea-8759-ec638ff90a43.png)

[analytics.tractmanager.com-1598627385593.log](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5142799/analytics.tractmanager.com-1598627385593.log)

**Comment by LyleEllerbach** [comment]
> Here is a snapshot of the console log as well as the full log saved to a .log file. Hope this helps.
> ![Console Log](https://user-images.githubusercontent.com/52171091/91583464-e17f7380-e916-11ea-8759-ec638ff90a43.png)
> 
> [analytics.tractmanager.com-1598627385593.log](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5142799/analytics.tractmanager.com-1598627385593.log)

On the screen print you can see the My Spend dashboard tab.  That dashboard does not have the Export All object.  When you click on that dashboard there is nothing logged in the console.

**Comment by haniunc** [comment]
> > Hi @craigbloodworth ,
> > In our dashboards, when it is first loaded, no data is selected and the user selects a practice from a drop down which populates the table. It seems like this is causing an issue with the blank export. If we have one pre-selected before we upload it to the server, it works fine. I can send you a packaged workbook to test this out. Another issue (also appearing in that workbook) is buttons that do nothing when you click on them. Should I use the same link above to send you the dashboard, or is there another link I should use?
> > Again, we are using Tableau 2020.1.0 and Chrome for the browser.
> 
> Thanks for the description @haniunc. That is a specific use case which is separate from the issues listed above. I can see how a recent change could cause this to happen. I can remove part of this change which should solve that specific use case. It's deploying now and will be live in the next few minutes

Awesome, thanks, we will test that when it's updated. 
As for the buttons that do nothing when pressed, can I send you the dashboard to take a look? Also, you can see the issue with the column ordering when updating a button. I have my fields numbered, and the even numbers appear first and then the odd numbered fields appear below them when configuring the button.

**Comment by LyleEllerbach** [comment]
Hello!  I hope you have had a nice weekend.   I have been continuing my testing and it looks like the issue of the refresh might have been resolved.  I will continue to test to confirm.   We are however, still having the issue of the order of the columns in the XLSX file not being what we defined in the Configure control.   After further inspection it looks like the issue might be that the Configure control is not saving the order change.  If I make some changes and the come back in the order is reverting back to some random order.

But it does look like the refresh has subsided so we are making progress!   Thanks for all your help in resolving these issues.  Our users are calling in hoping to get the Export features back online.   Thanks again! :-)

**Comment by elalios** [comment]
[Column_order_configuration.docx](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5150725/Column_order_configuration.docx)
Hello! Out tableau version is 2020.1.5 and the issue of not saving the column order remains. I'm attaching the steps we perform in order to change the order of our columns and as you may see the order is acting randomnly.

**Comment by craigbloodworth** [comment]
> [Column_order_configuration.docx](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5150725/Column_order_configuration.docx)
> Hello! Our tableau version is 2020.1.5 and the issue of not saving the column order remains. I'm attaching the steps we perform in order to change the order of our columns and as you may see the order is acting randomnly.

Thanks for the replication steps. Can you confirm whether you're using Desktop or Server? Also if I provide a location to securely drop a packaged workbook would you be willing to supply it for testing?

**Comment by elalios** [comment]
Hello! We are using tableau Desktop.

**Comment by craigbloodworth** [comment]
The issue regarding column ordering should now be fixed in v2.2.1

Please could you validate your side and I will close this issue.

**Comment by elalios** [comment]
Hello I can confirm that the column ordering is fixed 
Thanks

**Comment by LyleEllerbach** [comment]
Good morning!  Thank you for all your hard work.  It looks like we are stable with the refresh issue and are not having any more issues with column order.  Have a great day!
